spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_URL}
    password: ${DATABASE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

springdoc:
  swagger-ui:
    url: /v3/api-docs/swagger-config
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
