spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd-biblioteca
    username: postgres
    password: qwerty123
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080